export const BIBLE_BOOKS = [
  // Old Testament
  { name: 'Genesis', category: 'Pentateuch', chapters: 50 },
  { name: 'Exodus', category: 'Pentateuch', chapters: 40 },
  { name: 'Leviticus', category: 'Pentateuch', chapters: 27 },
  { name: 'Numbers', category: 'Pentateuch', chapters: 36 },
  { name: 'Deuteronomy', category: 'Pentateuch', chapters: 34 },
  { name: 'Joshua', category: 'History', chapters: 24 },
  { name: 'Judges', category: 'History', chapters: 21 },
  { name: 'Ruth', category: 'History', chapters: 4 },
  { name: '1 Samuel', category: 'History', chapters: 31 },
  { name: '2 Samuel', category: 'History', chapters: 24 },
  { name: '1 Kings', category: 'History', chapters: 22 },
  { name: '2 Kings', category: 'History', chapters: 25 },
  { name: '1 Chronicles', category: 'History', chapters: 29 },
  { name: '2 Chronicles', category: 'History', chapters: 36 },
  { name: 'Ezra', category: 'History', chapters: 10 },
  { name: 'Nehemiah', category: 'History', chapters: 13 },
  { name: 'Esther', category: 'History', chapters: 10 },
  { name: 'Job', category: 'Poetry', chapters: 42 },
  { name: 'Psalms', category: 'Poetry', chapters: 150 },
  { name: 'Proverbs', category: 'Poetry', chapters: 31 },
  { name: 'Ecclesiastes', category: 'Poetry', chapters: 12 },
  { name: 'Song of Solomon', category: 'Poetry', chapters: 8 },
  { name: 'Isaiah', category: 'Major Prophets', chapters: 66 },
  { name: 'Jeremiah', category: 'Major Prophets', chapters: 52 },
  { name: 'Lamentations', category: 'Major Prophets', chapters: 5 },
  { name: 'Ezekiel', category: 'Major Prophets', chapters: 48 },
  { name: 'Daniel', category: 'Major Prophets', chapters: 12 },
  { name: 'Hosea', category: 'Minor Prophets', chapters: 14 },
  { name: 'Joel', category: 'Minor Prophets', chapters: 3 },
  { name: 'Amos', category: 'Minor Prophets', chapters: 9 },
  { name: 'Obadiah', category: 'Minor Prophets', chapters: 1 },
  { name: 'Jonah', category: 'Minor Prophets', chapters: 4 },
  { name: 'Micah', category: 'Minor Prophets', chapters: 7 },
  { name: 'Nahum', category: 'Minor Prophets', chapters: 3 },
  { name: 'Habakkuk', category: 'Minor Prophets', chapters: 3 },
  { name: 'Zephaniah', category: 'Minor Prophets', chapters: 3 },
  { name: 'Haggai', category: 'Minor Prophets', chapters: 2 },
  { name: 'Zechariah', category: 'Minor Prophets', chapters: 14 },
  { name: 'Malachi', category: 'Minor Prophets', chapters: 4 },
  // New Testament
  { name: 'Matthew', category: 'Gospels', chapters: 28 },
  { name: 'Mark', category: 'Gospels', chapters: 16 },
  { name: 'Luke', category: 'Gospels', chapters: 24 },
  { name: 'John', category: 'Gospels', chapters: 21 },
  { name: 'Acts', category: 'History', chapters: 28 },
  { name: 'Romans', category: 'Epistles', chapters: 16 },
  { name: '1 Corinthians', category: 'Epistles', chapters: 16 },
  { name: '2 Corinthians', category: 'Epistles', chapters: 13 },
  { name: 'Galatians', category: 'Epistles', chapters: 6 },
  { name: 'Ephesians', category: 'Epistles', chapters: 6 },
  { name: 'Philippians', category: 'Epistles', chapters: 4 },
  { name: 'Colossians', category: 'Epistles', chapters: 4 },
  { name: '1 Thessalonians', category: 'Epistles', chapters: 5 },
  { name: '2 Thessalonians', category: 'Epistles', chapters: 3 },
  { name: '1 Timothy', category: 'Epistles', chapters: 6 },
  { name: '2 Timothy', category: 'Epistles', chapters: 4 },
  { name: 'Titus', category: 'Epistles', chapters: 3 },
  { name: 'Philemon', category: 'Epistles', chapters: 1 },
  { name: 'Hebrews', category: 'Epistles', chapters: 13 },
  { name: 'James', category: 'Epistles', chapters: 5 },
  { name: '1 Peter', category: 'Epistles', chapters: 5 },
  { name: '2 Peter', category: 'Epistles', chapters: 3 },
  { name: '1 John', category: 'Epistles', chapters: 5 },
  { name: '2 John', category: 'Epistles', chapters: 1 },
  { name: '3 John', category: 'Epistles', chapters: 1 },
  { name: 'Jude', category: 'Epistles', chapters: 1 },
  { name: 'Revelation', category: 'Prophecy', chapters: 22 },
];
